routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DashboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('user/login', ['title' => 'Login']);
})->name('login');

Route::get('register', [UserControllerntroller::class, 'register'])->name('register');
Route::post('register', [UserController::class, 'register_action'])->name('register.action');
Route::get('login', [UserController::class, 'login'])->name('login');
Route::post('login', [UserController::class, 'login_action'])->name('login.action');
Route::get('password', [UserController::class, 'password'])->name('password');
Route::post('password', [UserController::class, 'password_action'])->name('password.action');
Route::get('logout', [UserController::class, 'logout'])->name('logout');


Route::resource('dashboard', DashboardController::class);

app/Models/Pasien.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pasien extends Model
{
    use HasFactory;

    protected $table ='tb_pasien';
    protected $primaryKey ='id_pasien';

    protected $fillable=['nama_pasien','alamat','no_telpon', 'id_rs'];
}

app/Models/RumahSakit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class RumahSakit extends Model
{
    use HasFactory;

    public $table ='tb_rumah_sakit';
    protected $primaryKey ='id_rs';

    protected $fillable=['nama_rumah_sakit','alamat', 'email', 'telepon'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasFactory;

    protected $table ='tb_user';
    protected $primaryKey ='user_id';

    protected $fillable=['user_id', 'name','username','password'];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pasien;
use App\Models\RumahSakit;
use App\Models\User;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $title['title'] = 'Dashboard';
        // $data = RumahSakit::all();
        $data = RumahSakit::orderBy('id_rs', 'ASC')->get();
        return view('dashboard.home')->with('data', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Validateion Sebelum menyimpan ke database
        $request->validate([
            'nama_rumah_sakit' => 'required',
            'alamat' => 'required',
            'email' => 'required',
            'telepon' => 'required',
            // 'iamge' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:1028'
        ]);

        $data = new RumahSakit;
        // Request Data Form HTML create
        $data->nama_rumah_sakit = $request->nama_rumah_sakit;
        $data->alamat = $request->alamat;
        $data->email = $request->email;
        $data->telepon = $request->telepon;

        $data->save();
        return redirect()->route('dashboard.index')->with('success', 'Rumah Sakit Telah Ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id_rs)
    {
        // $data = new RumahSakit;
        // $data = $id_rs->find($id_rs);
        $data = RumahSakit::find($id_rs);

        // Request Data Form HTML create
        $data->nama_rumah_sakit = $request->nama_rumah_sakit;
        $data->alamat = $request->alamat;
        $data->email = $request->email;
        $data->telepon = $request->telepon;

        $data->save();
        return redirect()->route('dashboard.index')->with('success', 'Data Telah Berhasil Diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id_rs)
    {
        // RumahSakit::where('id_rs', $id_rs)->delete();
        $data = RumahSakit::find($id_rs);
        $data->delete();
        
        return response()->json([
            'status' => 'Data Telah Berhasil DiHapus',
        ]);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function register()
    {
        $data['title'] = 'Register';
        return view('user/register', $data);
    }

    public function register_action(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'username' => 'required|unique:tb_user',
            'password' => 'required',
            'password_confirm' => 'required|same:password',
        ]);

        $user = new User([
            'name' => $request->name,
            'username' => $request->username,
            'password' => Hash::make($request->password),
        ]);
        $user->save();

        return redirect()->route('login')->with('success', 'Registration success. Please login!');
    }


    public function login()
    {
        $data['title'] = 'Login';
        return view('user/login', $data);
    }

    public function login_action(Request $request)
    {
        $request->validate([
            'username' => 'required',
            'password' => 'required',
        ]);
        if (Auth::attempt(['username' => $request->username, 'password' => $request->password])) {
            $request->session()->regenerate();
            return redirect()->intended('dashboard');
        }

        return back()->withErrors([
            'password' => 'Wrong username or password',
        ]);
    }

    public function password()
    {
        $data['title'] = 'Change Password';
        return view('user/password', $data);
    }

    public function password_action(Request $request)
    {
        $request->validate([
            'old_password' => 'required|current_password',
            'new_password' => 'required|confirmed',
        ]);
        $user = User::find(Auth::id());
        $user->password = Hash::make($request->new_password);
        $user->save();
        $request->session()->regenerate();
        return back()->with('success', 'Password changed!');
    }

    public function logout(Request $request)
    {
        Auth::logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();
        return redirect('/');
    }
}

resources/views/app.blade.php
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <title>@yield('title', $title)</title>

    <style>
        body {
        background-color: white;
        };
    </style>
    
</head>

<body>
    <div class="container">
        <h1>@yield('title', $title)</h1>
        @yield('content')
    </div>
    @yield('index')



</body>
<script src="{{ asset('js/app.js') }}"></script>
</html>

resources/views/dashboard/create.blade.php
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">
    <style>
        body {
            background-color: white;
        }

        ;
    </style>

</head>

<body>
    <div class="container">
        <h1>Selamat Datang</h1>
        @yield('content')
        @yield('index')
        @auth
        <p>Welcome <b>{{ Auth::user()->name }}</b></p>
        <!-- <a class="btn btn-primary" href="{{ route('password') }}">Change Password</a> -->
        <a class="btn btn-danger" href="{{ route('logout') }}">Logout</a>
        @endauth
        @guest
        <a class="btn btn-primary" href="{{ route('login') }}">Login</a>
        <a class="btn btn-info" href="{{ route('register') }}">Register</a>
        @endguest

        @if($errors->any())
        @foreach($errors->all() as $err)
        <p class="alert alert-danger">{{ $err }}</p>
        @endforeach
        @endif

        <div class="mb-3 mt-5">
            <a href="{{ route('dashboard.index')}}" class="btn btn-outline-primary">
                << Kembali</a>
        </div>

        <form action="{{ route('dashboard.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="container mb-3 mt-5">
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Nama Rumah Sakit</label>
                    <input type="text" class="form-control" name="nama_rumah_sakit" id="nama_rumah_sakit" placeholder="Nama Rumah Sakit...">
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Email</label>
                    <input type="email" class="form-control" name="email" id="email" placeholder="Email Rumah Sakit...">
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">No Telepon</label>
                    <input type="text" class="form-control" name="telepon" id="telepon" placeholder="No Telepon Rumah Sakit...">
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Alamat</label>
                    <textarea class="form-control" name="alamat" id="alamat" rows="3" placeholder="Nama Rumah Sakit..."></textarea>
                </div>
            </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <button class="btn btn-primary">Simpan</button>
            </div>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script>
        function showFile(event) {
            var input = event.target;
            var reader = new FileReader();
            reader.onload = function() {
                var dataURL = reader.result;
                var output = document.getElementById('file-preview');
                output.src = dataURL;
            };
            reader.readAsDataURL(input.files[0]);
        }
    </script>
</body>

</html>

resources/views/dashboard/home.blade.php
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">
    <style>
        body {
            background-color: white;
        }

        ;
    </style>

</head>

<body>
    <div class="container">
        <h1>Selamat Datang</h1>
        @yield('content')
        @yield('index')
        
        @auth
        <p>Welcome <b>{{ Auth::user()->name }}</b></p>
        <!-- <a class="btn btn-primary" href="{{ route('password') }}">Change Password</a> -->
        <a class="btn btn-danger" href="{{ route('logout') }}">Logout</a>
        <div class=" mb-3 mt-5">
            <a href="" class="btn btn-outline-primary">Lihat Data Pasien</a>
            <a href="{{ route('dashboard.create') }}" class="btn btn-primary">Add Rumah Sakit</a>
        </div>
        @endauth

        @guest
        <a class="btn btn-primary" href="{{ route('login') }}">Login</a>
        <a class="btn btn-info" href="{{ route('register') }}">Register</a>
        @endguest

        
        @if($message = Session::get('success'))

        <p class="alert alert-success">{{ $message }}</p>

        @endif

        <table class="table table-striped" style="width:100%" id="example">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Nama Rumah Sakit</th>
                    <th>Alamat</th>
                    <th>Email</th>
                    <th>Telepon</th>
                    <th>Action</th>
                </tr>
            </thead>

            <tbody>
                @foreach($data as $key => $item)
                <tr>
                    <input type="hidden" class="DeleteUsr_val" value="{{$item->id_rs}}">
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $item->nama_rumah_sakit }}</td>
                    <td>{{ $item->alamat }}</td>
                    <td>{{ $item->email }}</td>
                    <td>{{ $item->telepon }}</td>
                    <td>
                        <!-- <a class="btn btn-outline-primary" href="{{ url('/dashboard/'.$item->id_rs) }}">Detail</a> -->

                        <!-- Button trigger modal Detail -->
                        <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#ButtonDetail{{$item->id_rs}}">
                            Detail
                        </button>
                        <!-- Modal Detail-->
                        <div class="modal fade" id="ButtonDetail{{$item->id_rs}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">Data Rumah Sakit</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <form>
                                            <!-- <input type="text" class="form-control" id="e_id" name="id" value="{{$item->id_rs}}" /> -->
                                            <fieldset disabled>
                                                <div class="mb-3">
                                                    <label for="disabledTextInput" class="form-label">Nama Rumah Sakit</label>
                                                    <input type="text" id="disabledTextInput" id="e_name" class="form-control" value="{{$item->nama_rumah_sakit}}">
                                                </div>
                                                <div class="mb-3">
                                                    <label for="disabledSelect" class="form-label">Alamat</label>
                                                    <input type="text" id="disabledTextInput" class="form-control" value="{{$item->alamat}}">
                                                </div>
                                                <div class="mb-3">
                                                    <label for="disabledSelect" class="form-label">Email</label>
                                                    <input type="text" id="disabledTextInput" class="form-control" value="{{$item->email}}">
                                                </div>
                                                <div class="mb-3">
                                                    <label for="disabledSelect" class="form-label">Telepon</label>
                                                    <input type="text" id="disabledTextInput" class="form-control" value="{{$item->telepon}}">
                                                </div>
                                            </fieldset>
                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- <a class="btn btn-primary" href="{{ url('/dashboard/'.$item->id_rs) }}">Edit</a> -->

                        <!-- Button trigger modal Update-->
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#ButtonEdit{{$item->id_rs}}">
                            Edit
                        </button>
                        <!-- Modal Update-->
                        <div class="modal fade" id="ButtonEdit{{$item->id_rs}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">Edit Data Rumah Sakit</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <form action="{{ route('dashboard.update', $item->id_rs) }}" method="POST" enctype="multipart/form-data">
                                            <!-- <input type="text" class="form-control" id="e_id" name="id" value="{{$item->id_rs}}" /> -->
                                            @csrf
                                            @method('PUT')
                                            <div class="mb-3">
                                                <label for="InputName" class="form-label">Nama Rumah Sakit</label>
                                                <input type="text" name="nama_rumah_sakit" class="form-control" value="{{$item->nama_rumah_sakit}}">
                                            </div>
                                            <div class="mb-3">
                                                <label for="InputAlamat" class="form-label">Alamat</label>
                                                <input type="text" name="alamat" class="form-control" value="{{$item->alamat}}">
                                            </div>
                                            <div class="mb-3">
                                                <label for="InputEmail" class="form-label">Email</label>
                                                <input type="email" name="email" class="form-control" value="{{$item->email}}">
                                            </div>
                                            <div class="mb-3">
                                                <label for="InputTelepon" class="form-label">Telepon</label>
                                                <input type="text" name="telepon" class="form-control" value="{{$item->telepon}}">
                                            </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-primary">Update</button>
                                    </div>
                                    </form>
                                </div>
                            </div>
                        </div>

                        <button type="button" class="btn btn-danger DeleteData">DELETE</button>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script>
        let table = new DataTable('#example');
    </script>

    <!-- <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script> -->

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        $(document).ready(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
                }
            });

            $(`.DeleteData`).click(function(e) {
                e.preventDefault();

                var id_rs = $(this).closest("tr").find(`.DeleteUsr_val`).val();
                // alert(id_rs);
                Swal.fire({
                        title: 'Are you sure?',
                        text: "You won't be able to revert this!",
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Yes, delete it!'
                    })
                    .then((willDelete) => {
                        if (willDelete.isConfirmed) {
                            var data = {
                                "_token": $('input[name=_token]').val(),
                                "id": id_rs,
                            };
                            $.ajax({
                                type: "DELETE",
                                url: `/dashboard/`+id_rs,
                                data: data,
                                success: function(response) {
                                    Swal.fire(
                                            'Deleted!',
                                            'Your file has been deleted.',
                                            'success'
                                        )
                                        .then((result) => {
                                            location.reload();
                                        });
                                }
                            });
                        }
                    });
            });
        });
    </script>
</body>

</html>

resources/views/dashboard/show.blade.php
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <style>
        body {
            background-color: white;
        }

        ;
    </style>

</head>

<body>
    <div class="container">
        <h1>Selamat Datang</h1>
        @yield('content')
        @yield('index')
        @auth
        <p>Welcome <b>{{ Auth::user()->name }}</b></p>
        <!-- <a class="btn btn-primary" href="{{ route('password') }}">Change Password</a> -->
        <a class="btn btn-danger" href="{{ route('logout') }}">Logout</a>
        @endauth
        @guest
        <a class="btn btn-primary" href="{{ route('login') }}">Login</a>
        <a class="btn btn-info" href="{{ route('register') }}">Register</a>
        @endguest

        <div class="mb-3 mt-5">
            <h1>{{ $data->nama_rumah_sakit }}</h1>
            <p>
                <b>Id Rumah Sakit</b> {{ $data->id_rs }}
            </p>
            <h1>{{ $data->alamat }}</h1>
            <p>
                <b>Id Rumah Sakit</b> {{ $data->id_rs }}
            </p>
            <a href="" class="btn btn-primary">Add Rumah Sakit</a>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Nama Rumah Sakit</th>
                    <th>Alamat</th>
                    <th>Email</th>
                    <th>Telepon</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $key => $item)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $item->nama_rumah_sakit }}</td>
                    <td>{{ $item->alamat }}</td>
                    <td>{{ $item->email }}</td>
                    <td>{{ $item->telepon }}</td>
                    <td>
                        <a class="btn btn-outline-primary" href="{{ url('/dashboard/'.$item->id_rs) }}">Detail</a>
                        <a  class="btn btn-primary" href="{{ url('/dashboard/'.$item->id_rs) }}">Edit</a>
                        <button class="btn btn-danger btn-delete" data-id="{{ $item->id_rs }}">Delete</button>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

        
        <div class="mb-3 mt-5">
            <a href="" class="btn btn-outline-primary">Lihat Data Pasien</a>
        </div>
    </div>





</body>
<script src="{{ asset('js/app.js') }}"></script>

</html>

resources/views/user/login.blade.php
@extends('app')
@section('content')
<div class="row justify-content-around mx-auto p-5">
    <div class="col-12">
        <div class="row justify-content-around mx-auto p-5">
            <img src="{{ asset('img/logo-login.jpg') }}" alt="Deskripsi Gambar" 
            style="width: 300px;">
        </div>
    </div>
    <div class="col-4">
        <div class="card-body">
            <h5 class="card-title text-center">@section('content')</h5>
            @if(session('success'))
            <p class="alert alert-success">{{ session('success') }}</p>
            @endif
            @if($errors->any())
            @foreach($errors->all() as $err)
            <p class="alert alert-danger">{{ $err }}</p>
            @endforeach
            @endif
            <form action="{{ route('login.action') }}" method="POST">
                @csrf
                <div class="mb-3">
                    <label for="exampleInputUsername1" class="form-label">Username <span class="text-danger">*</span></label>
                    <input type="username" name="username" placeholder="Ketikkan Username Anda...." class="form-control" value="{{ old('username') }}" id="exampleInputUsername1" aria-describedby="usernameHelp">
                    <div id="usernameHelp" class="form-text">Silahkan Login dengan menggunakan username</div>
                </div>
                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Password <span class="text-danger">*</span></label>
                    <input type="password" name="password" placeholder="Ketikkan Password Anda...." class="form-control" id="exampleInputPassword1">
                </div>

                <div class="container">
                    <div class="row justify-content-between">

                        <div class="d-grid gap-1">
                            <button class="btn btn-outline-primary">Login</button>

                        </div>

                        <!-- <div class="col-md-3 offset-md-4"> 
                                        <button type="button" class="btn btn-outline-primary">Register</button>
                                    </div> -->
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/user/password.blade.php
@extends('app')
@section('content')
<div class="row">
    <div class="col-md-6">
        @if(session('success'))
        <p class="alert alert-success">{{ session('success') }}</p>
        @endif
        @if($errors->any())
        @foreach($errors->all() as $err)
        <p class="alert alert-danger">{{ $err }}</p>
        @endforeach
        @endif
        <form action="{{ route('password.action') }}" method="POST">
            @csrf
            <div class="mb-3">
                <label>Password <span class="text-danger">*</span></label>
                <input class="form-control" type="password" name="old_password" />
            </div>
            <div class="mb-3">
                <label>New Password <span class="text-danger">*</span></label>
                <input class="form-control" type="password" name="new_password" />
            </div>
            <div class="mb-3">
                <label>New Password Confirmation<span class="text-danger">*</span></label>
                <input class="form-control" type="password" name="new_password_confirmation" />
            </div>
            <div class="mb-3">
                <button class="btn btn-primary">Change</button>
                <a class="btn btn-danger" href="{{ route('index') }}">Back</a>
            </div>
        </form>
    </div>
</div>
@endsection